project:
  name: quickstart-wordpress-serverless
  owner: saif.ali@sudoconsultants.com
  package_lambda: false
  shorten_stack_name: true
  s3_regional_buckets: true
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-east-1
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - me-south-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-2
    - us-west-1
  parameters:
    VPCCIDR: 10.0.0.0/16
    PrivateSubnet1CIDR: 10.0.0.0/19
    PrivateSubnet2CIDR: 10.0.32.0/19
    PrivateSubnet3CIDR: 10.0.64.0/19
    PublicSubnet1CIDR: 10.0.96.0/20
    PublicSubnet2CIDR: 10.0.128.0/20
    PublicSubnet3CIDR: 10.0.160.0/20
    DBUsername: override
    DBPassword: $[taskcat_genpass_16A]
    DBName: $[taskcat_random-string]
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  new-vpc-wordpress-2az:
    template: templates/main-entrypoint-new-vpc.template.yaml
    parameters:
      NumberOfAZs: "2"
      AvailabilityZones: $[taskcat_genaz_2]
    regions:
      - ap-northeast-1
      - ap-south-1
      - ap-southeast-1
      - eu-central-1
      - eu-west-3
  new-vpc-wordpress-3az:
    template: templates/main-entrypoint-new-vpc.template.yaml
    parameters:
      NumberOfAZs: "3"
      AvailabilityZones: $[taskcat_genaz_3]
    regions:
      - us-east-1
      - us-east-2
      - us-west-2
